For our baseline, I implemented the Logistic Regression model.
We used BERT-based sentence embeddings to represent each post as a 384-dimensional vector.
This model is fast and interpretable, making it a good starting point.
It achieved an overall accuracy of around 72% with balanced F1-scores across all classes.
From the confusion matrix, we saw it performed especially well in detecting Bipolar and Anxiety categories.
This baseline helped us understand the dataset’s separability and guided our tuning for more complex models later.

In [1]:
from google.colab import files
uploaded = files.upload()

Saving preprocessed_data.csv to preprocessed_data.csv


In [ ]:
import pandas as pd, numpy as np, joblib
from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# 1️Load Data
df = pd.read_csv("preprocessed_data.csv").dropna(subset=["processed_text","target"]).reset_index(drop=True)
X = df["processed_text"].tolist()
y = df["target"]

# 2️ Embeddings
model = SentenceTransformer("all-MiniLM-L6-v2")
X_emb = model.encode(X, batch_size=32, show_progress_bar=True)

# 3️ Split
X_train, X_test, y_train, y_test = train_test_split(X_emb, y, test_size=0.2, random_state=42, stratify=y)

# 4️ Model
clf = LogisticRegression(max_iter=2000, multi_class="multinomial", random_state=42)
clf.fit(X_train, y_train)

# 5️ Evaluate
y_pred = clf.predict(X_test)
print("=== Logistic Regression (Baseline) ===")
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/158 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


=== Logistic Regression (Baseline) ===
              precision    recall  f1-score   support

           0       0.84      0.72      0.77       189
           1       0.61      0.66      0.63       187
           2       0.75      0.73      0.74       203
           3       0.68      0.70      0.69       208
           4       0.73      0.77      0.75       224

    accuracy                           0.72      1011
   macro avg       0.72      0.72      0.72      1011
weighted avg       0.72      0.72      0.72      1011

[[136  14   3  13  23]
 [  9 123  18  24  13]
 [  4  21 148  16  14]
 [  4  38   8 145  13]
 [  9   7  20  15 173]]
